select * from customer limit 20

-- 1. What is the total revenue generated by male vs female customers?

select gender, SUM(purchase_amount) as revenue
from customer
group by gender




-- 2. Which customers used a discount but still spent more than the average purchase amount?

select AVG(purchase_amount) from customer

-- AVG = 59.7643589743589744

select customer_id, purchase_amount, discount_applied
from customer
where discount_applied = 'Yes' and purchase_amount > (select AVG(purchase_amount) from customer)

-- Query showing all customers who used a discount but still spent more than the average purchase amount
-- No query returns any customer using discount that spent money lower than AVG(59.7643589743589744)




-- 3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(AVG(review_rating::numeric), 2) as "Average Product Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5




-- 4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, ROUND(AVG(purchase_amount), 2) as "Average Purchased Amounts"
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type




-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, 
COUNT(customer_id) as "Total Customer", 
ROUND(AVG(purchase_amount), 2) as "Average Spend", 
ROUND(SUM(purchase_amount), 2) as "Total Revenue"
from customer
group by subscription_status




-- 6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, 
ROUND(((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100)/COUNT(*)), 2) as discount_rates
from customer
group by item_purchased
order by discount_rates desc
limit 5




-- 7. Segment customers into New, Returning, and Loyal based on their number of previous purchases, and show the count of each segment.

-- Giving number of previous purchases = 1 is New
-- 							 purchases = 2-10 times is Returning
-- 							 purchases = >10 times is Loyal

with customer_type as(
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	WHEN previous_purchases > 10 THEN 'Loyal'
END AS customer_segment
from customer
)

select customer_segment, COUNT(*) as "Number of customers"
from customer_type
group by customer_segment




-- 8. What are the top 3 most purchased products within each category?

with item_counts as(
select category,
item_purchased,
COUNT(item_purchased) as total_orders,
ROW_NUMBER() over(partition by category order by COUNT(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3




-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscibe?

select subscription_status as "Subscribers", COUNT(customer_id) as "Repeat Buyers"
from customer
where previous_purchases > 5
group by subscription_status




-- 10. What is the revenue contribution of each age group?

select age_group, SUM(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc